INSERT INTO hero(_id,localized_name,name) SELECT '1' as _id,'Anti-Mage' as localized_name,'npc_dota_hero_antimage' as name
UNION ALL SELECT '2','Axe','npc_dota_hero_axe'
UNION ALL SELECT '3','Bane','npc_dota_hero_bane'
UNION ALL SELECT '4','Bloodseeker','npc_dota_hero_bloodseeker'
UNION ALL SELECT '5','Crystal Maiden','npc_dota_hero_crystal_maiden'
UNION ALL SELECT '6','Drow Ranger','npc_dota_hero_drow_ranger'
UNION ALL SELECT '7','Earthshaker','npc_dota_hero_earthshaker'
UNION ALL SELECT '8','Juggernaut','npc_dota_hero_juggernaut'
UNION ALL SELECT '9','Mirana','npc_dota_hero_mirana'
UNION ALL SELECT '11','Shadow Fiend','npc_dota_hero_nevermore'
UNION ALL SELECT '10','Morphling','npc_dota_hero_morphling'
UNION ALL SELECT '12','Phantom Lancer','npc_dota_hero_phantom_lancer'
UNION ALL SELECT '13','Puck','npc_dota_hero_puck'
UNION ALL SELECT '14','Pudge','npc_dota_hero_pudge'
UNION ALL SELECT '15','Razor','npc_dota_hero_razor'
UNION ALL SELECT '16','Sand King','npc_dota_hero_sand_king'
UNION ALL SELECT '17','Storm Spirit','npc_dota_hero_storm_spirit'
UNION ALL SELECT '18','Sven','npc_dota_hero_sven'
UNION ALL SELECT '19','Tiny','npc_dota_hero_tiny'
UNION ALL SELECT '20','Vengeful Spirit','npc_dota_hero_vengefulspirit'
UNION ALL SELECT '21','Windranger','npc_dota_hero_windrunner'
UNION ALL SELECT '22','Zeus','npc_dota_hero_zuus'
UNION ALL SELECT '23','Kunkka','npc_dota_hero_kunkka'
UNION ALL SELECT '25','Lina','npc_dota_hero_lina'
UNION ALL SELECT '31','Lich','npc_dota_hero_lich'
UNION ALL SELECT '26','Lion','npc_dota_hero_lion'
UNION ALL SELECT '27','Shadow Shaman','npc_dota_hero_shadow_shaman'
UNION ALL SELECT '28','Slardar','npc_dota_hero_slardar'
UNION ALL SELECT '29','Tidehunter','npc_dota_hero_tidehunter'
UNION ALL SELECT '30','Witch Doctor','npc_dota_hero_witch_doctor'
UNION ALL SELECT '32','Riki','npc_dota_hero_riki'
UNION ALL SELECT '33','Enigma','npc_dota_hero_enigma'
UNION ALL SELECT '34','Tinker','npc_dota_hero_tinker'
UNION ALL SELECT '35','Sniper','npc_dota_hero_sniper'
UNION ALL SELECT '36','Necrophos','npc_dota_hero_necrolyte'
UNION ALL SELECT '37','Warlock','npc_dota_hero_warlock'
UNION ALL SELECT '38','Beastmaster','npc_dota_hero_beastmaster'
UNION ALL SELECT '39','Queen of Pain','npc_dota_hero_queenofpain'
UNION ALL SELECT '40','Venomancer','npc_dota_hero_venomancer'
UNION ALL SELECT '41','Faceless Void','npc_dota_hero_faceless_void'
UNION ALL SELECT '42','Wraith King','npc_dota_hero_skeleton_king'
UNION ALL SELECT '43','Death Prophet','npc_dota_hero_death_prophet'
UNION ALL SELECT '44','Phantom Assassin','npc_dota_hero_phantom_assassin'
UNION ALL SELECT '45','Pugna','npc_dota_hero_pugna'
UNION ALL SELECT '46','Templar Assassin','npc_dota_hero_templar_assassin'
UNION ALL SELECT '47','Viper','npc_dota_hero_viper'
UNION ALL SELECT '48','Luna','npc_dota_hero_luna'
UNION ALL SELECT '49','Dragon Knight','npc_dota_hero_dragon_knight'
UNION ALL SELECT '50','Dazzle','npc_dota_hero_dazzle'
UNION ALL SELECT '51','Clockwerk','npc_dota_hero_rattletrap'
UNION ALL SELECT '52','Leshrac','npc_dota_hero_leshrac'
UNION ALL SELECT '53','Nature''s Prophet','npc_dota_hero_furion'
UNION ALL SELECT '54','Lifestealer','npc_dota_hero_life_stealer'
UNION ALL SELECT '55','Dark Seer','npc_dota_hero_dark_seer'
UNION ALL SELECT '56','Clinkz','npc_dota_hero_clinkz'
UNION ALL SELECT '57','Omniknight','npc_dota_hero_omniknight'
UNION ALL SELECT '58','Enchantress','npc_dota_hero_enchantress'
UNION ALL SELECT '59','Huskar','npc_dota_hero_huskar'
UNION ALL SELECT '60','Night Stalker','npc_dota_hero_night_stalker'
UNION ALL SELECT '61','Broodmother','npc_dota_hero_broodmother'
UNION ALL SELECT '62','Bounty Hunter','npc_dota_hero_bounty_hunter'
UNION ALL SELECT '63','Weaver','npc_dota_hero_weaver'
UNION ALL SELECT '64','Jakiro','npc_dota_hero_jakiro'
UNION ALL SELECT '65','Batrider','npc_dota_hero_batrider'
UNION ALL SELECT '66','Chen','npc_dota_hero_chen'
UNION ALL SELECT '67','Spectre','npc_dota_hero_spectre'
UNION ALL SELECT '69','Doom','npc_dota_hero_doom_bringer'
UNION ALL SELECT '68','Ancient Apparition','npc_dota_hero_ancient_apparition'
UNION ALL SELECT '70','Ursa','npc_dota_hero_ursa'
UNION ALL SELECT '71','Spirit Breaker','npc_dota_hero_spirit_breaker'
UNION ALL SELECT '72','Gyrocopter','npc_dota_hero_gyrocopter'
UNION ALL SELECT '73','Alchemist','npc_dota_hero_alchemist'
UNION ALL SELECT '74','Invoker','npc_dota_hero_invoker'
UNION ALL SELECT '75','Silencer','npc_dota_hero_silencer'
UNION ALL SELECT '76','Outworld Devourer','npc_dota_hero_obsidian_destroyer'
UNION ALL SELECT '77','Lycan','npc_dota_hero_lycan'
UNION ALL SELECT '78','Brewmaster','npc_dota_hero_brewmaster'
UNION ALL SELECT '79','Shadow Demon','npc_dota_hero_shadow_demon'
UNION ALL SELECT '80','Lone Druid','npc_dota_hero_lone_druid'
UNION ALL SELECT '81','Chaos Knight','npc_dota_hero_chaos_knight'
UNION ALL SELECT '82','Meepo','npc_dota_hero_meepo'
UNION ALL SELECT '83','Treant Protector','npc_dota_hero_treant'
UNION ALL SELECT '84','Ogre Magi','npc_dota_hero_ogre_magi'
UNION ALL SELECT '85','Undying','npc_dota_hero_undying'
UNION ALL SELECT '86','Rubick','npc_dota_hero_rubick'
UNION ALL SELECT '87','Disruptor','npc_dota_hero_disruptor'
UNION ALL SELECT '88','Nyx Assassin','npc_dota_hero_nyx_assassin'
UNION ALL SELECT '89','Naga Siren','npc_dota_hero_naga_siren'
UNION ALL SELECT '90','Keeper of the Light','npc_dota_hero_keeper_of_the_light'
UNION ALL SELECT '91','Io','npc_dota_hero_wisp'
UNION ALL SELECT '92','Visage','npc_dota_hero_visage'
UNION ALL SELECT '93','Slark','npc_dota_hero_slark'
UNION ALL SELECT '94','Medusa','npc_dota_hero_medusa'
UNION ALL SELECT '95','Troll Warlord','npc_dota_hero_troll_warlord'
UNION ALL SELECT '96','Centaur Warrunner','npc_dota_hero_centaur'
UNION ALL SELECT '97','Magnus','npc_dota_hero_magnataur'
UNION ALL SELECT '98','Timbersaw','npc_dota_hero_shredder'
UNION ALL SELECT '99','Bristleback','npc_dota_hero_bristleback'
UNION ALL SELECT '100','Tusk','npc_dota_hero_tusk'
UNION ALL SELECT '101','Skywrath Mage','npc_dota_hero_skywrath_mage'
UNION ALL SELECT '102','Abaddon','npc_dota_hero_abaddon'
UNION ALL SELECT '103','Elder Titan','npc_dota_hero_elder_titan'
UNION ALL SELECT '104','Legion Commander','npc_dota_hero_legion_commander'
UNION ALL SELECT '105','Techies','npc_dota_hero_techies'
UNION ALL SELECT '106','Ember Spirit','npc_dota_hero_ember_spirit'
UNION ALL SELECT '107','Earth Spirit','npc_dota_hero_earth_spirit'
UNION ALL SELECT '109','Terrorblade','npc_dota_hero_terrorblade'
UNION ALL SELECT '110','Phoenix','npc_dota_hero_phoenix'
UNION ALL SELECT '111','Oracle','npc_dota_hero_oracle'
UNION ALL SELECT '112','Winter Wyvern','npc_dota_hero_winter_wyvern';